version: "3.8" 

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-arun}"
    image: cybulde-model-training
    container_name: cybulde-model-training-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-arunkumar}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #   - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-arunkumar}/.config/gcloud
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ipc: host
    init: true